apiVersion: v1
kind: Service
metadata:
  name: quotes-service  #service name
  namespace: default
spec:
  selector:
    app: quotes
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
